-- Expansão do catálogo: polias, máquinas e barra (academia completa)
INSERT INTO exercise_catalog
  (slug, nome, grupo_muscular, padrao_movimento, nivel_grupo, locais, equipamentos, instrucoes, erros_comuns, validado_por, ativo)
VALUES

-- ── PEITO ────────────────────────────────────────────────────────────────────
('supino-barra-reto',
 'Supino Reto com Barra',
 'peito', 'push', 'intermediario',
 ARRAY['academia'],
 ARRAY['barra', 'rack', 'banco'],
 'Deite no banco, pegue a barra com pegada um pouco mais larga que os ombros. Desça controlado até tocar levemente o peito e empurre até extensão quase completa.',
 'Não bater a barra no peito; manter escápulas retraídas e pés apoiados no chão.',
 'guilherme', true),

('supino-barra-inclinado',
 'Supino Inclinado com Barra',
 'peito', 'push', 'intermediario',
 ARRAY['academia'],
 ARRAY['barra', 'banco inclinado', 'rack'],
 'Banco a 30-45°. Desça a barra até a parte superior do peito, cotovelos em ~75°. Empurre de volta.',
 'Não abrir demais os cotovelos; manter lombar neutra sem arquear excessivamente.',
 'guilherme', true),

('crossover-polia-alta',
 'Crossover na Polia Alta',
 'peito', 'push', 'intermediario',
 ARRAY['academia'],
 ARRAY['polia', 'cabo'],
 'Polia na posição alta. De frente para o aparelho, incline levemente o tronco. Puxe os cabos em arco cruzando na frente do corpo na altura do umbigo.',
 'Não dobrar o cotovelo para mais de 20°; o movimento deve ser amplo e controlado.',
 'carlos', true),

('peck-deck',
 'Peck Deck (Voador)',
 'peito', 'push', 'iniciante',
 ARRAY['academia'],
 ARRAY['máquina peck deck'],
 'Sente-se com as costas apoiadas. Posicione os antebraços nas almofadas. Feche os braços à frente do peito com contração máxima, abra controlado.',
 'Não levar o peso além do ponto de conforto no ombro; manter a lombar encostada.',
 'carlos', true),

-- ── COSTAS ───────────────────────────────────────────────────────────────────
('puxada-frontal-polia',
 'Puxada Frontal na Polia',
 'costas', 'pull', 'iniciante',
 ARRAY['academia'],
 ARRAY['polia', 'cabo', 'barra puxada'],
 'Sente-se com as coxas travadas. Pegue a barra com pegada pronada larga. Puxe até a barra tocar a parte superior do peito, cotovelos apontando para baixo.',
 'Não jogar o tronco para trás; não encurtar a amplitude no retorno.',
 'guilherme', true),

('puxada-neutra-polia',
 'Puxada Neutra (Triângulo)',
 'costas', 'pull', 'iniciante',
 ARRAY['academia'],
 ARRAY['polia', 'cabo', 'triângulo'],
 'Pegada neutra no triângulo. Puxe até o triângulo tocar o esterno, cotovelos passando pelas laterais do tronco. Volte controlado.',
 'Não arredondar o ombro no topo; manter o peito aberto durante todo o movimento.',
 'guilherme', true),

('remada-cabo-sentado',
 'Remada Baixa no Cabo',
 'costas', 'pull', 'iniciante',
 ARRAY['academia'],
 ARRAY['polia', 'cabo', 'triângulo'],
 'Sente-se na poltrona, pés apoiados. Puxe o cabo até o abdômen retraindo as escápulas. Estenda os braços controlando o peso de volta.',
 'Não usar o tronco como balanço; manter coluna neutra durante todo o movimento.',
 'carlos', true),

('remada-barra-curvada',
 'Remada Curvada com Barra',
 'costas', 'pull', 'intermediario',
 ARRAY['academia'],
 ARRAY['barra', 'anilhas'],
 'Quadril dobrado ~45°, joelhos levemente flexionados. Puxe a barra até o abdômen retraindo escápulas. Coluna neutra o tempo todo.',
 'Não arredondar o lombar; não usar momentum excessivo dos quadris.',
 'guilherme', true),

-- ── BÍCEPS ───────────────────────────────────────────────────────────────────
('rosca-barra',
 'Rosca Direta com Barra',
 'biceps', 'pull', 'iniciante',
 ARRAY['academia'],
 ARRAY['barra', 'anilhas'],
 'Em pé, pegada supinada na barra. Flexione o cotovelo trazendo a barra até a altura dos ombros. Desça controlado sem balançar o tronco.',
 'Não jogar o tronco para trás; manter os cotovelos fixos ao lado do corpo.',
 'guilherme', true),

('rosca-scott',
 'Rosca Scott (Preacher Curl)',
 'biceps', 'pull', 'intermediario',
 ARRAY['academia'],
 ARRAY['barra scott', 'anilhas', 'banco scott'],
 'Apoie os cotovelos na almofada do banco Scott. Flexione completamente, depois desça com controle total — não estenda além de 170° para proteger o tendão.',
 'Não soltar o peso abruptamente na extensão; arco completo é fundamental.',
 'carlos', true),

('rosca-cabo-polia',
 'Rosca no Cabo (Polia Baixa)',
 'biceps', 'pull', 'iniciante',
 ARRAY['academia'],
 ARRAY['polia', 'cabo', 'barra reta'],
 'Polia na posição baixa com barra reta ou corda. Flexione o cotovelo, contraia o bíceps no topo e desça com tensão constante do cabo.',
 'Manter cotovelos fixos; o cabo garante tensão máxima em toda a amplitude.',
 'carlos', true),

-- ── TRÍCEPS ──────────────────────────────────────────────────────────────────
('pushdown-corda-polia',
 'Pushdown com Corda na Polia',
 'triceps', 'push', 'iniciante',
 ARRAY['academia'],
 ARRAY['polia', 'cabo', 'corda'],
 'Polia alta com corda. Cotovelos fixos ao lado do corpo, estenda os antebraços para baixo abrindo levemente a corda no final para contração máxima.',
 'Não afastar os cotovelos do corpo; não usar o ombro para empurrar.',
 'guilherme', true),

('skull-crusher-barra',
 'Skull Crusher com Barra',
 'triceps', 'push', 'intermediario',
 ARRAY['academia'],
 ARRAY['barra', 'anilhas', 'banco'],
 'Deitado no banco, barra acima do peito. Flexione apenas o cotovelo descendo a barra até próximo da testa. Estenda de volta sem mover o ombro.',
 'Não abrir o cotovelo para os lados; não descer rápido demais.',
 'carlos', true),

-- ── QUADRÍCEPS ───────────────────────────────────────────────────────────────
('leg-press-45',
 'Leg Press 45°',
 'quadriceps', 'squat', 'iniciante',
 ARRAY['academia'],
 ARRAY['leg press 45'],
 'Pés na plataforma na largura dos ombros ou um pouco mais. Desça até 90° de flexão do joelho sem que o lombar saia do apoio. Empurre de volta sem travar o joelho.',
 'Não enrolar o lombar no ponto mais baixo; não trancar o joelho no topo.',
 'guilherme', true),

('cadeira-extensora',
 'Cadeira Extensora',
 'quadriceps', 'push', 'iniciante',
 ARRAY['academia'],
 ARRAY['cadeira extensora'],
 'Sente-se ajustando o encosto e o rolo na frente do tornozelo. Estenda o joelho completamente com contração do quadríceps, desça em 2-3 segundos.',
 'Não usar impulso; não hiperextender o joelho; manter as costas encostadas.',
 'carlos', true),

('agachamento-barra',
 'Agachamento com Barra (Low Bar)',
 'quadriceps', 'squat', 'intermediario',
 ARRAY['academia'],
 ARRAY['barra', 'rack', 'anilhas'],
 'Barra posicionada nos trapézios posteriores. Pés na largura dos ombros, pontas levemente abertas. Desça até coxa paralela ao chão mantendo o joelho alinhado com o pé.',
 'Não dobrar o tronco excessivamente; não colapsar os joelhos para dentro.',
 'guilherme', true),

-- ── POSTERIOR ────────────────────────────────────────────────────────────────
('mesa-flexora',
 'Mesa Flexora (Leg Curl)',
 'posterior', 'hinge', 'iniciante',
 ARRAY['academia'],
 ARRAY['mesa flexora'],
 'Deite de bruços ajustando o rolo atrás do tornozelo. Flexione o joelho trazendo o calcanhar em direção aos glúteos. Desça controlado sem bater o peso.',
 'Não levantar o quadril da mesa; não usar força dos lombares.',
 'carlos', true),

('leg-curl-pe',
 'Leg Curl em Pé',
 'posterior', 'hinge', 'iniciante',
 ARRAY['academia'],
 ARRAY['cadeira leg curl'],
 'Em pé no aparelho, rolo atrás do tornozelo. Flexione o joelho em amplitude completa, mantenha o quadril fixo. Desça com controle.',
 'Não jogar o quadril para trás ao subir; manter o tronco estável.',
 'guilherme', true),

-- ── OMBROS ───────────────────────────────────────────────────────────────────
('elevacao-lateral-cabo',
 'Elevação Lateral no Cabo',
 'ombros', 'push', 'intermediario',
 ARRAY['academia'],
 ARRAY['polia', 'cabo'],
 'Polia baixa do lado oposto ao braço. Eleve o braço lateralmente até a altura do ombro com cotovelo levemente flexionado. O cabo garante tensão contínua.',
 'Não elevar além de 90°; não usar o trapézio para "subir" o braço.',
 'carlos', true),

('desenvolvimento-barra',
 'Desenvolvimento com Barra (Military Press)',
 'ombros', 'push', 'intermediario',
 ARRAY['academia'],
 ARRAY['barra', 'rack', 'anilhas'],
 'Em pé ou sentado, barra na altura do queixo com pegada larga. Empurre verticalmente até extensão quase completa. Desça até a barra passar abaixo do queixo.',
 'Não arquear excessivamente o lombar; não inclinar o tronco para compensar.',
 'guilherme', true)

ON CONFLICT (slug) DO NOTHING;
