-- Expansão do catálogo: exercícios avançado e atleta para academia completa
INSERT INTO exercise_catalog
  (slug, nome, grupo_muscular, padrao_movimento, nivel_grupo, locais, equipamentos, instrucoes, erros_comuns, validado_por, ativo)
VALUES

-- ── QUADRÍCEPS — AVANÇADO ────────────────────────────────────────────────────
('agachamento-frontal',
 'Agachamento Frontal com Barra',
 'quadriceps', 'squat', 'avancado',
 ARRAY['academia'],
 ARRAY['barra', 'rack', 'anilhas'],
 'Barra apoiada na clavícula com pegada cruzada ou em gaiola. Cotovelos altos, tronco mais vertical que no agachamento convencional. Desça até abaixo do paralelo, joelhos acompanham a ponta dos pés.',
 'Não deixar os cotovelos caírem; não projetar o tronco para frente; manter o núcleo rígido.',
 'guilherme', true),

('pistol-squat',
 'Pistol Squat (Agachamento Unilateral)',
 'quadriceps', 'squat', 'atleta',
 ARRAY['academia'],
 ARRAY['peso corporal', 'halteres'],
 'Em pé sobre uma perna, estenda a outra à frente. Desça controlado até o quadril abaixo do joelho, mantenha o outro pé elevado. Suba empurrando o calcanhar contra o chão.',
 'Não deixar o joelho colapsar para dentro; manter o tronco ereto; controlar a descida sem queda.',
 'guilherme', true),

('agachamento-pausa',
 'Agachamento com Pausa no Fundo',
 'quadriceps', 'squat', 'avancado',
 ARRAY['academia'],
 ARRAY['barra', 'rack', 'anilhas'],
 'Agachamento convencional com pausa de 2-3 segundos no ponto mais baixo (coxa paralela ou abaixo). Elimina o reflexo de estiramento, exige força máxima na saída.',
 'Não relaxar a tensão do núcleo na pausa; não usar rebote para subir; manter posição dos joelhos.',
 'carlos', true),

('leg-press-unilateral',
 'Leg Press 45° Unilateral',
 'quadriceps', 'squat', 'avancado',
 ARRAY['academia'],
 ARRAY['leg press 45'],
 'Uma perna no centro da plataforma. Desça controlado até 90° de flexão do joelho, empurre de volta sem travar. Trabalha desequilíbrios entre os lados.',
 'Não enrolar o lombar; não deixar o joelho colapsar; controlar a descida mais que no bilateral.',
 'guilherme', true),

-- ── GLÚTEOS — INTERMEDIÁRIO / AVANÇADO ──────────────────────────────────────
('hip-thrust-barra',
 'Hip Thrust com Barra',
 'gluteos', 'hinge', 'intermediario',
 ARRAY['academia'],
 ARRAY['barra', 'anilhas', 'banco'],
 'Costas apoiadas no banco, barra sobre o quadril com pad de proteção. Pés afastados na largura dos ombros. Empurre o quadril para cima contraindo os glúteos no topo. Desça controlado.',
 'Não arquear a lombar no topo; não deixar os joelhos colapsarem; não usar a lombar para "subir".',
 'guilherme', true),

('agachamento-sumo-pesado',
 'Agachamento Sumô com Barra',
 'gluteos', 'squat', 'intermediario',
 ARRAY['academia'],
 ARRAY['barra', 'rack', 'anilhas'],
 'Pés muito afastados, pontas voltadas para fora (~45°). Barra nas costas (high bar). Descida com o tronco mais vertical, joelhos seguem as pontas dos pés. Ativa intensamente adutores e glúteos.',
 'Não deixar os joelhos fecharem; manter o arco lombar; não inclinar o tronco à frente.',
 'carlos', true),

('rdl-unilateral',
 'RDL Unilateral (Single-Leg Romanian Deadlift)',
 'gluteos', 'hinge', 'avancado',
 ARRAY['academia'],
 ARRAY['halteres', 'barra'],
 'Em pé sobre uma perna, haltere na mão oposta. Inclina o tronco à frente elevando a perna livre para trás como contrapeso. Volte pelo glúteo da perna de apoio. Mantém quadril nivelado.',
 'Não rotacionar o quadril ao elevar a perna; manter a coluna neutra; não dobrar demais o joelho de apoio.',
 'guilherme', true),

('kickback-cabo',
 'Kickback no Cabo (Extensão de Quadril)',
 'gluteos', 'hinge', 'intermediario',
 ARRAY['academia'],
 ARRAY['polia', 'cabo', 'caneleira cabo'],
 'Caneleira do cabo no tornozelo, polia baixa. Incline levemente o tronco segurando o suporte. Empurre a perna para trás em extensão de quadril, contraindo o glúteo no topo. Volte controlado.',
 'Não arquear o lombar para elevar a perna; manter a pelve estável; amplitude controlada.',
 'carlos', true),

('afundo-bulgaro',
 'Afundo Búlgaro (Split Squat)',
 'gluteos', 'squat', 'avancado',
 ARRAY['academia'],
 ARRAY['halteres', 'banco'],
 'Pé traseiro elevado no banco. Desça com o joelho da frente alinhado ao pé, quadril para baixo. Suba empurrando o calcanhar da frente contra o chão. Amplitude completa.',
 'Não deixar o joelho da frente ultrapassar demais a ponta do pé; manter o tronco ligeiramente inclinado à frente; pelve neutra.',
 'guilherme', true),

-- ── POSTERIOR DE COXA — AVANÇADO ─────────────────────────────────────────────
('good-morning-barra',
 'Good Morning com Barra',
 'posterior', 'hinge', 'avancado',
 ARRAY['academia'],
 ARRAY['barra', 'rack', 'anilhas'],
 'Barra nas costas como agachamento. Joelhos levemente flexionados. Incline o tronco à frente dobrando no quadril até quase horizontal, mantendo a coluna reta. Volte pelo posterior e glúteos.',
 'Não arredondar a lombar; não dobrar demais os joelhos; carga leve no início pois é alta alavanca.',
 'guilherme', true),

('nordic-curl',
 'Nordic Curl (Inversão de Perna Nórdica)',
 'posterior', 'hinge', 'atleta',
 ARRAY['academia'],
 ARRAY['banco', 'suporte nordico'],
 'Joelhos no chão, tornozelos presos sob o banco. Descida lentíssima para frente controlando apenas com o posterior de coxa. Use as mãos para empurrar no final da descida e retornar.',
 'Não deixar o quadril quebrar; manter o tronco alinhado com as coxas; trabalhar a fase excêntrica ao máximo.',
 'carlos', true),

('hyperextensao-banco-romano',
 'Hiperextensão no Banco Romano',
 'posterior', 'hinge', 'intermediario',
 ARRAY['academia'],
 ARRAY['banco romano'],
 'Quadril apoiado na almofada, pernas presas. Desça o tronco controlado até ~90° e suba estendendo a coluna até o alinhamento neutro (não além). Pode segurar anilha no peito para sobrecarregar.',
 'Não hiperextender acima da linha neutra; não arredondar a lombar; movimento lento e controlado.',
 'guilherme', true),

-- ── PEITO — AVANÇADO ──────────────────────────────────────────────────────────
('supino-declinado-barra',
 'Supino Declinado com Barra',
 'peito', 'push', 'avancado',
 ARRAY['academia'],
 ARRAY['barra', 'banco declinado', 'rack'],
 'Banco declinado (~30°), pés presos. Barra desce até a parte inferior do peito (abaixo do mamilo). Empurre de volta em arco. Ativa intensamente a porção inferior do peitoral.',
 'Atenção ao unrack/rerack — mais difícil nessa posição; não deixar os ombros antecipar; spotters recomendados.',
 'guilherme', true),

('mergulho-paralelas-peso',
 'Mergulho nas Paralelas com Peso',
 'peito', 'push', 'avancado',
 ARRAY['academia'],
 ARRAY['barras paralelas', 'cinto de peso', 'anilhas'],
 'Nas barras paralelas com peso preso ao cinto ou halter entre as pernas. Incline levemente o tronco à frente para ativar o peitoral. Desça até os ombros abaixo dos cotovelos. Empurre de volta.',
 'Não balançar o corpo; não descer além do conforto do ombro; cotovelos levemente abertos.',
 'guilherme', true),

('supino-pegada-fechada',
 'Supino Pega Fechada (Close Grip Bench)',
 'triceps', 'push', 'avancado',
 ARRAY['academia'],
 ARRAY['barra', 'banco', 'rack'],
 'Pegada um pouco mais estreita que os ombros. Cotovelos próximos ao corpo na descida. Barra desce até o peito, empurre vertical. Foco no tríceps mas também trabalha peito interior.',
 'Não fechar demais a pegada (risco de pulso); manter os cotovelos abaixo de 45° do tronco; escápulas retraídas.',
 'carlos', true),

-- ── COSTAS — AVANÇADO ──────────────────────────────────────────────────────────
('remada-pendlay',
 'Remada Pendlay com Barra',
 'costas', 'pull', 'avancado',
 ARRAY['academia'],
 ARRAY['barra', 'anilhas'],
 'Barra no chão, tronco paralelo ao solo. Puxe explosivamente a barra até o abdômen retraindo as escápulas. Retorne completamente ao chão a cada repetição (sem bounce). Exige força máxima.',
 'Não usar rebote do chão; manter a coluna neutra com tronco paralelo; explosão real na puxada.',
 'guilherme', true),

('barra-fixa-peso',
 'Barra Fixa com Peso Adicional',
 'costas', 'pull', 'avancado',
 ARRAY['academia'],
 ARRAY['barra fixa', 'cinto de peso', 'anilhas'],
 'Peso preso no cinto ou halter entre as pernas. Pegada pronada larga. Puxe até o queixo ultrapassar a barra. Desça com controle total até extensão completa dos braços.',
 'Não balançar; não meio-repetição (extensão completa em baixo é fundamental); ritmo controlado.',
 'carlos', true),

('remada-barra-t',
 'Remada na Barra T (T-Bar Row)',
 'costas', 'pull', 'avancado',
 ARRAY['academia'],
 ARRAY['barra t', 'anilhas', 'suporte t-bar'],
 'Peito apoiado no suporte inclinado, pega no triângulo ou alça V. Puxe as anilhas em direção ao peito retraindo as escápulas. Desça controlado com extensão completa dos braços.',
 'Não usar o tronco como balanço; não arredondar a lombar; manter a contração no topo.',
 'guilherme', true),

('remada-yates',
 'Remada Yates (Supinada com Barra)',
 'costas', 'pull', 'avancado',
 ARRAY['academia'],
 ARRAY['barra', 'anilhas'],
 'Tronco levemente inclinado (~70°), pegada supinada na barra. Puxe até o abdômen baixo com cotovelos próximos ao corpo. Posição mais ereta que a remada curvada clássica.',
 'Não arredondar a lombar; manter a inclinação consistente; ativação de bíceps secundária é normal.',
 'carlos', true),

-- ── OMBROS — AVANÇADO ─────────────────────────────────────────────────────────
('push-press',
 'Push Press com Barra',
 'ombros', 'push', 'avancado',
 ARRAY['academia'],
 ARRAY['barra', 'rack', 'anilhas'],
 'Em pé, barra na frente dos ombros. Dê um leve impulso (dip) com as pernas e empurre a barra verticalmente até extensão completa. Receba a barra com os joelhos levemente flexionados.',
 'Não usar flexão excessiva de joelhos (vira agachamento); manter o tronco vertical; controlar a descida.',
 'guilherme', true),

('face-pull-corda-pesado',
 'Face Pull com Corda Pesado',
 'ombros', 'pull', 'avancado',
 ARRAY['academia'],
 ARRAY['polia', 'cabo', 'corda'],
 'Polia na altura do rosto ou ligeiramente acima. Puxe a corda em direção ao rosto dividindo as pontas para os lados ao final. Rotação externa máxima no topo. Essencial para saúde do manguito rotador.',
 'Não usar carga excessiva que comprometa a amplitude; separar bem as pontas da corda no final; cotovelos altos.',
 'carlos', true),

('desenvolvimento-arnold',
 'Desenvolvimento Arnold',
 'ombros', 'push', 'avancado',
 ARRAY['academia'],
 ARRAY['halteres', 'banco'],
 'Sentado, halteres na altura dos ombros com palmas viradas para o rosto. Ao empurrar, gire os punhos para fora chegando à posição supinada no topo. Inverta na descida.',
 'Não usar impulso do tronco; controlar a rotação; não sobrecarregar além da amplitude confortável do ombro.',
 'guilherme', true),

-- ── BÍCEPS — AVANÇADO ─────────────────────────────────────────────────────────
('rosca-spider',
 'Rosca Spider (Banco Inclinado a 45°)',
 'biceps', 'pull', 'avancado',
 ARRAY['academia'],
 ARRAY['halteres', 'banco inclinado'],
 'Deitado de bruços no banco a 45°, braços pendurados perpendiculares ao solo. Rosca com halteres em amplitude completa sem apoio do tronco. Elimina compensação do ombro.',
 'Não balançar o corpo; extensão completa no baixo; contração máxima no topo.',
 'carlos', true),

('rosca-inclinada',
 'Rosca Inclinada com Halteres',
 'biceps', 'pull', 'avancado',
 ARRAY['academia'],
 ARRAY['halteres', 'banco inclinado'],
 'Sentado no banco inclinado (~60°), braços pendurados naturalmente. Flexione alternadamente ou simultâneo. A posição inclinada aumenta o alongamento inicial do bíceps.',
 'Não jogar os cotovelos para frente; deixar o braço extensão completa em baixo; amplitude máxima.',
 'guilherme', true),

('chin-up-peso',
 'Chin-Up com Peso (Barra Fixa Supinada)',
 'biceps', 'pull', 'atleta',
 ARRAY['academia'],
 ARRAY['barra fixa', 'cinto de peso', 'anilhas'],
 'Pegada supinada (palmas para você) na barra fixa, largura dos ombros. Com peso adicional, puxe até o queixo ultrapassar a barra. Ativa fortemente bíceps e latíssimo.',
 'Extensão completa dos braços em baixo; não balançar para ganhar impulso; desça com controle total.',
 'carlos', true),

-- ── TRÍCEPS — AVANÇADO ────────────────────────────────────────────────────────
('jm-press',
 'JM Press com Barra',
 'triceps', 'push', 'atleta',
 ARRAY['academia'],
 ARRAY['barra', 'banco', 'anilhas'],
 'Deitado no banco, barra acima da linha dos ombros. Desça a barra em direção ao pescoço/mandíbula flexionando os cotovelos (combinação de skull crusher e supino fechado). Empurre de volta.',
 'Não levar a barra ao nariz (risco de lesão); mantenha os cotovelos apontados para cima; peso moderado.',
 'guilherme', true),

('extensao-triceps-cabo-unilateral',
 'Extensão de Tríceps Unilateral no Cabo',
 'triceps', 'push', 'intermediario',
 ARRAY['academia'],
 ARRAY['polia', 'cabo'],
 'Polia alta, alça simples. Um braço de cada vez, cotovelo fixo ao lado da cabeça. Estenda completamente o antebraço para baixo. Permite maior amplitude que a versão bilateral.',
 'Manter o cotovelo apontado para cima e fixo; não usar o ombro para ajudar; extensão total.',
 'carlos', true),

-- ── PANTURRILHA — AVANÇADO ────────────────────────────────────────────────────
('panturrilha-leg-press',
 'Panturrilha no Leg Press',
 'panturrilha', 'push', 'iniciante',
 ARRAY['academia'],
 ARRAY['leg press 45'],
 'No leg press 45° com as pernas quase estendidas, apenas a ponta do pé na borda inferior da plataforma. Faça a flexão plantar completa. Permite carga muito maior que a panturrilha em pé.',
 'Não deixar o platform cair além de neutro (risco de lesão na panturrilha); amplitude completa.',
 'guilherme', true),

('panturrilha-sentado-maquina',
 'Panturrilha Sentado na Máquina',
 'panturrilha', 'push', 'iniciante',
 ARRAY['academia'],
 ARRAY['máquina panturrilha sentado'],
 'Sentado com almofada sobre as coxas, ponta dos pés na beira da plataforma. Eleve os calcanhares o máximo possível. Pausa no topo. Foca especificamente no solear (músculo profundo).',
 'Não usar impulso; amplitude completa em cima e embaixo; o solear responde bem a repetições mais altas.',
 'carlos', true),

-- ── CORE — AVANÇADO / ATLETA ───────────────────────────────────────────────────
('ab-wheel-rollout-pe',
 'Ab Wheel Rollout em Pé',
 'core', 'core', 'atleta',
 ARRAY['academia'],
 ARRAY['ab wheel'],
 'Em pé com o ab wheel à frente. Role para frente controlando com o core até quase paralelo ao solo. Retorne contraindo os abdominais. Variação extremamente difícil do rollout de joelhos.',
 'Começar pelo rollout de joelhos primeiro; não ceder na lombar; manter quadril ligeiramente para cima.',
 'guilherme', true),

('dragon-flag',
 'Dragon Flag',
 'core', 'core', 'atleta',
 ARRAY['academia'],
 ARRAY['banco'],
 'Deitado no banco segurando as barras atrás da cabeça. Levante o corpo reto como uma tábua usando apenas os ombros como ponto de apoio. Desça controlado sem tocar o banco. Exige core de elite.',
 'Não dobrar o quadril (corpo deve ficar completamente reto); a descida é mais difícil que a subida; construir força progressivamente.',
 'carlos', true),

('pallof-press',
 'Pallof Press no Cabo',
 'core', 'core', 'avancado',
 ARRAY['academia'],
 ARRAY['polia', 'cabo'],
 'De lado para a polia, cabo na altura do peito. Segure com ambas as mãos próximas ao peito. Estenda os braços à frente resistindo à rotação, depois retorne. Anti-rotação do core.',
 'Manter o corpo perpendicular à polia; não rotacionar o tronco ao estender; respiração controlada.',
 'guilherme', true),

('prancha-com-peso',
 'Prancha com Anilha nas Costas',
 'core', 'core', 'avancado',
 ARRAY['academia'],
 ARRAY['anilhas'],
 'Posição de prancha forearm com anilha posicionada entre as escápulas por um parceiro. Mantenha o alinhamento perfeito do corpo com o peso adicional. Progressão da prancha clássica.',
 'Não deixar o quadril subir ou cair; respiração controlada; começar com peso leve e progredir.',
 'carlos', true),

-- ── ATLETA — MOVIMENTOS OLÍMPICOS / FORÇA TOTAL ─────────────────────────────
('terra-romeno-barra',
 'Terra Romeno com Barra (RDL)',
 'posterior', 'hinge', 'intermediario',
 ARRAY['academia'],
 ARRAY['barra', 'anilhas'],
 'Barra à frente dos quadris, pegada pronada na largura dos ombros. Incline o tronco para frente com os joelhos levemente flexionados (fixos), descendo a barra ao longo das pernas até sentir o alongamento do posterior. Volte pelo quadril.',
 'Não arredondar a lombar; não dobrar os joelhos demais (seria agachamento); barra sempre rente às pernas.',
 'guilherme', true),

('farmer-carry',
 'Farmer''s Carry (Marcha do Agricultor)',
 'core', 'core', 'avancado',
 ARRAY['academia'],
 ARRAY['halteres pesados', 'kettlebell', 'trap bar'],
 'Segure pesos pesados em cada mão. Caminhe com passos firmes mantendo o tronco ereto e o core contraído. Desenvolve força de agarre, core e capacidade cardiovascular de forma única.',
 'Não inclinar para os lados; passos controlados; ombros para baixo e para trás; respiração constante.',
 'carlos', true),

('thruster',
 'Thruster com Barra',
 'quadriceps', 'squat', 'atleta',
 ARRAY['academia'],
 ARRAY['barra', 'rack', 'anilhas'],
 'Barra na frente dos ombros. Agache completamente e no momento de subir, use o impulso das pernas para empurrar a barra verticalmente acima da cabeça até extensão total. Movimento contínuo.',
 'Sincronizar a transição do agachamento para o desenvolvimento; manter os cotovelos altos; core rígido durante toda a execução.',
 'guilherme', true),

('clean-parcial',
 'Clean Parcial (Power Clean)',
 'costas', 'hinge', 'atleta',
 ARRAY['academia'],
 ARRAY['barra', 'anilhas'],
 'Barra no chão, posição de terra. Puxe explosivamente com extensão de quadril e joelhos, encolha sob a barra recebendo-a nos deltoides. Joelhos dobrados na recepção. Exige técnica apurada.',
 'Aprender com peso leve primeiro; puxada deve ser vertical; cotovelos devem girar rapidamente para receber a barra; quadris como mola principal.',
 'guilherme', true),

('agachamento-overhead',
 'Agachamento Overhead (OHS)',
 'quadriceps', 'squat', 'atleta',
 ARRAY['academia'],
 ARRAY['barra', 'anilhas'],
 'Barra presa acima da cabeça com pegada larga (posição de arranque). Agache com a barra estabilizada overhead. Exige mobilidade extrema de tornozelo, quadril, ombros e torácica.',
 'Não usar carga elevada sem mobilidade adequada; manter os braços completamente estendidos; torácica estendida.',
 'carlos', true),

('terra-deficit',
 'Levantamento Terra com Déficit',
 'posterior', 'hinge', 'atleta',
 ARRAY['academia'],
 ARRAY['barra', 'anilhas', 'plataforma'],
 'Em pé sobre uma plataforma elevada (5-10cm), realize o terra convencional. O déficit aumenta a amplitude de movimento exigindo mais força do posterior na saída do chão.',
 'Não usar o déficit sem domínio do terra convencional; amplitude aumentada exige maior mobilidade; manter a coluna neutra em posição mais desafiadora.',
 'guilherme', true)

ON CONFLICT (slug) DO NOTHING;
